### PR TITLE
  [R4R]Feature/backport geth native trace

### PR DESCRIPTION
**Pull request by jsvisa**
### Description

The Geth native trace has a 
There is a significant performance improvement  with Geth's native trace, release in [Release Vallhallan Threshold (v1.10.12) · ethereum/go-ethereum](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.12), and the specific implementation code is in the two PR:

- [eth/tracers: support for golang tracers + add golang callTracer by s1na · Pull Request #23708 · ethereum/go-ethereum](https://github.com/ethereum/go-ethereum/pull/23708)
- [eth/tracers: make native call tracer default by s1na · Pull Request #23867 · ethereum/go-ethereum](https://github.com/ethereum/go-ethereum/pull/23867)
- [core,eth: call frame tracing by s1na · Pull Request #23087 · ethereum/go-ethereum](https://github.com/ethereum/go-ethereum/pull/23087)
- [eth/tracers: package restructuring by holiman · Pull Request #23857 · ethereum/go-ethereum](https://github.com/ethereum/go-ethereum/pull/23857)

In our BSC Archive node tests, we found that the CPU usage was reduced from 40% to 10%(20cores reduced to 2 cores)

wecom-temp-d2a905b448436faa0b02dfc0b1859344

### Rationale

Follow in Geth's footsteps and speed up block synchronization

### Example

add an example CLI or API response...

### Changes

Notable changes: 
* Switch the call tracer to a fast native Go implementation
* Fixed some data errors with trace in the original JS version

### CODE REVIEW

**Comment by guagualvcha** [comment]
@jsvisa  Thanks a lot.  I will start looking into this PR.

**Comment by jsvisa** [comment]
@guagualvcha thanks for your reply, I will fix the Unit test failure later today

**Comment by jsvisa** [comment]
fixed the golang-lint, @guagualvcha PTAL

**Comment by guagualvcha** [comment]
@yutianwu  @kyrie-yl  Please help review this PR.

**Comment by guagualvcha** [comment]
Please cherry-pick this commit to fix the block context race issue. https://github.com/guagualvcha/bsc/commit/a6e619d0b8da8f211a92f3af7edd27939fe9967c

**Comment by guagualvcha** [comment]
LGTM. @jsvisa Thanks

**Review by guagualvcha — APPROVED** [review]

**Review by yutianwu — APPROVED** [review]

**Review by kyrie-yl — APPROVED** [review]

**Review by Jemerald83 — APPROVED** [review]

**Pull request merged**
